### ISSUE TITLE
Stop letter_opener when seeding the DB

### ISSUE THREAD

**Issue by davidmles** [ryanb/letter_opener#117] opened 2015-11-09 11:50 UTC
Is it possible to stop letter_opener when seeding the DB?

I have added this snippet at the beginning of my `seeds.rb` file:

```ruby
ActionMailer::Base.perform_deliveries = false
ActionMailer::Base.delivery_method = :smtp
```

But lots of windows open. No matter where I move that snippet, I have tried to place it just before the code that triggers those emails, but I have the same problem.

This is happening on my development environment.

**Comment by jwgoh** [comment] 2015-11-11 10:02
You can put them in the environment-specific configuration files, namely `config/environments/development.rb`.

```ruby
# Turn off deliveries
config.action_mailer.perfom_deliveries = false
```

**Comment by davidmles** [comment] 2015-11-11 10:11
Thanks, it worked. I hope this helps people coming here with the same issue :)

**Comment by davidmles** [comment] 2015-11-11 10:22
Uhm... it's working because I have disabled it for development. So if it's disabled for development, what's the point for letter_opener? It's intended for the development environment, so this solution is not ideal.

I'm reopening the issue.

**Comment by jwgoh** [comment] 2015-11-11 12:44
Well, you can disable `letter_opener` when seeding your db and re-enable it again after the seeding is done. How often do you "seed" your db? The only time I seed is when I am creating a new database. Am I missing out on something here?

**Comment by davidmles** [comment] 2015-11-11 12:47
I seed it more often, because I create and update my models several times. What's more, other (non-technical) people in the team follow the instructions in the Readme to seed the DB.

That's what we are going to do, but since it's not ideal I would love to know another more suitable solution.

**Comment by nashby** [comment] 2015-11-12 17:01
@davidmles can you try to change delivery method from `:smtp` to `:test`?

**Comment by davidmles** [comment] 2015-11-12 18:25
@nashby I just tried it, same problem.

Let me know if you need me to do something to debug this, please.

**Comment by nashby** [comment] 2015-11-13 19:48
@davidmles that's strange. Actually it works with adding only `ActionMailer::Base.perform_deliveries = false` to the seeds file for me. Can you please provide a sample application that reproduces the error?

**Comment by davidmles** [comment] 2015-11-15 23:24
I have tried it with a new application, and it actually works.

I'm thinking it's because I use Sidekiq. Maybe that cannot be controlled by the `perform_deliveries` option? Disabling Sidekiq when seeding obviously works, and that's the fix for my issue for now.

If that's the reason, I'm happy to close the issue.

**Comment by nashby** [comment] 2015-11-15 23:36
@davidmles hmm, that's strange. Looking at the code I can see that sidekiq uses `deliver` method which respects `perform_deliveries` option. What version of rails and sidekiq are you using?

**Comment by davidmles** [comment] 2015-11-15 23:37
I'm using the latest version of Rails and Sidekiq, and using the deliver_later method.
I will test it better tomorrow.

**Comment by davidmles** [comment] 2015-11-18 07:58
Steps to reproduce the issue:

* Create a new Rails application
* Add these requirements to the Gemfile:
```ruby
gem 'sidekiq'
gem 'sinatra', require: nil
group :development do
  gem 'letter_opener'
end
```
* Add sidekiq.yml to your config folder:
```yml
---
:concurrency: 5
:queues:
  - mailers
  - default
```
* Configure letter_opener in config/environments/development.rb:
```ruby
config.action_mailer.delivery_method = :letter_opener
```
* Add app/mailers/application_mailer.rb:
```ruby
class ApplicationMailer < ActionMailer::Base
  def sample_email
    mail from: 'example@example.org', to: 'example@example.com', subject: 'This is an example'
  end
end
```
* Add app/views/application_mailer/sample_email.html.erb:
```
This is an example.
```
* Add this to the db/seeds.rb file:
```ruby
ActionMailer::Base.perform_deliveries = false
ApplicationMailer.sample_email.deliver_later
```
* Start Redis: ```redis-server /usr/local/etc/redis.conf```
* Start Sidekiq: ```bundle exec sidekiq```
* Start the Rails server: ```rails s```
* Run the seeds file: ```bundle exec rake db:seed```

You should see the email actually being sent and letter opener opening it in a browser.

**Comment by jwgoh** [comment] 2015-11-23 13:03
Hmmm `deliver_now` doesn't seem to deliver the email for me. I modified the sample_email method to take in an optional parameter to differentiate the emails sent out (if there are 2).
```ruby
ActionMailer::Base.perform_deliveries = false
ApplicationMailer.sample_email.deliver_later
ApplicationMailer.sample_email("Now").deliver_now # no email
```

**Comment by davidmles** [comment] 2015-11-23 13:26
Yes, as @jwgoh says, `deliver_now` does not send the email, but `deliver_later` does.

Is this bug related to letter_opener? Or is it something Sidekiq is not doing correctly? Or maybe a Rails bug? What do you think @nashby ?

**Comment by shadwell** [comment] 2015-11-27 17:55
@davidmies Sidekiq will be running a separate instance of the environment so it will still have the usual configuration of `perform_deliveries=true`. 

You've only set that deliveries won't be performed in the instance of the environment where your seeds are being executed. That's why deliver_now isn't sending them: because it is running in the thread where you've set mails not to be delivered.

**Comment by davidmles** [comment] 2015-11-27 18:02
Thanks @shadwell, that makes sense. So, isn't it possible to deny it to send them using `deliver_later`?

**Comment by shadwell** [comment] 2015-11-27 18:08
No, not by temporarily changing the configuration I think. You've have to temporarily change it in the thread that actually sends the emails. You may have more luck skipping the actual delivery of the emails when seeding rather than trying to get letter_opener to suppress its delivery.

**Comment by nashby** [comment] 2016-01-30 13:37
@davidmles is it still an issue for you? I think you can try to disable sidekiq in the seed file somehow since you don't really need it there, do you?. Probably this would work https://github.com/mperham/sidekiq/wiki/Testing. Closing this for now.

**Closed by nashby** 2016-01-30 13:37 UTC

**Comment by jackkinsella** [comment] 2019-11-21 15:03
I'm late to the party on this one, but for what it's worth, my solution was to create a separate Rails environment `seed.rb` that inherits from development as [per a technique from DHH](https://signalvnoise.com/posts/3535-beyond-the-default-rails-environments). Within this env file, I changed the relevant settings in a way that can handle running separate processes (although I also disable the job queue and make it `inline` instead).

```ruby
require Rails.root.join('config/environments/development_base')

Rails.application.configure do
  # Avoid async difficulties when seeding data
  Rails.application.config.active_job.queue_adapter = :inline
  Rails.application.config.delivery_method = :test
  Rails.application.config.perform_deliveries = false
end
```

**Comment by hakunin** [comment] 2020-04-09 06:53
Rather than having to rely on an extra environment, I just disable these in my seed script:

```ruby
ActiveJob::Base.queue_adapter = :inline
ActionMailer::Base.delivery_method = :test
ActionMailer::Base.perform_deliveries = false
```
