### ISSUE TITLE
Add support for Windows 10 WSL

### ISSUE THREAD

**Issue by jamesst20** [ryanb/letter_opener#156] opened 2018-10-22 13:26 UTC
Hi,

It is currently possible from WSL to open a web browser in host (Windows 10). I was wondering if it could be supported by letter opener as well?

More info : https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux/1266038

Currently in WSL, running "explorer.exe http://google.ca" from anywhere open the url in my default browser.

This : export BROWSER='/mnt/c/Windows/explorer.exe' only opens an Explorer window when an email is sent.

This : export BROWSER='/mnt/c/Program\ Files\ (x86)/Google/Chrome/Application/chrome.exe'
opens a chrome window to file://mnt/c/Linux/SmartGit/securicheck/tmp/letter_opener/1540214727_835665_4904238/rich.html
It works if I replace /mnt/c by C:/.

Thank you

**Comment by jamesst20** [comment] 2018-12-06 13:48
To add extra information.. WSLView from WSLU is not compatible either even though it's meant for that. I am getting :

Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start file:////mnt/c/Linux/SmartGit/securicheck/tmp/letter_opener/154 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by nashby** [comment] 2018-12-09 11:03
@jamesst20 hey! Unfortunately I don't have a machine with Windows 10 so can't really help you but pull request is welcome!

**Comment by axvm** [comment] 2018-12-20 03:35
The issue is not in letter opener. Launchy doesn't support wsl https://github.com/copiousfreetime/launchy/issues/117

**Comment by nashby** [comment] 2019-06-16 20:32
@jamesst20 hey! Have you solved this somehow?

**Comment by jamesst20** [comment] 2019-06-16 20:36
@nashy

Sorry I didn't investigate deeper

**Comment by nashby** [comment] 2019-09-01 14:13
Closing this because it looks like Launchy's issue.

**Closed by nashby** 2019-09-01 14:13 UTC

**Comment by Taeir** [comment] 2021-03-24 12:15
I found a solution to this problem and explained it here: https://github.com/copiousfreetime/launchy/issues/117?_pjax=%23js-repo-pjax-container#issuecomment-805730312

**Comment by trebeil** [comment] 2024-05-28 03:12
I needed to change two files to make it work.

On _.bashrc_:
`export BROWSER=/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe`

On _config/environments/development.rb_:
```
LetterOpener.configure do |config|
  config.file_uri_scheme = 'file://wsl.localhost/Ubuntu'
end
```

What comes after _file:_ on the file_uri_scheme may be different for you. You can find it out typing on the console:
`wslpath -m '/'`
